Implement detection of redundant launcher execution
openbase/jul pull request #89
Opened 2023-01-08 20:11 UTC by DivineThreepwood

### :scroll: Description

* Switch to latest openbase type version v1.4
* Implement detection of redundant launcher execution.
* Implement LauncherRemote.
* Setup launcher as controller again and start controller service.
* Make sure launcher does not initialize if already started.

### Note
* Sorry for reformatting the entire `AbstractLauncher` class. Idea did this is background and I detected the changes to late to fully revert them.

2023-01-09 19:18 UTC, pLeminoq requested changes
The PR looks good overall, but it definitely needs a unit test and/or testing in a live system. With this PR, simply launching `bco-test` fails on my machine while it works on the dev branch.

2023-01-09 19:18 UTC, pLeminoq commented on module/pattern/launch/src/main/java/org/openbase/jul/pattern/launch/AbstractLauncher.java
> +                // this is the default since no other instant should be launched yet.
```suggestion
                // this is the default since no other instance should be launched yet.
```

2023-01-09 19:18 UTC, pLeminoq commented on module/pattern/launch/src/main/java/org/openbase/jul/pattern/launch/AbstractLauncher.java
> +    }
I know this is not part of this PR but why aren't these methods called `interruptLaunch` and `isLaunching`?

2023-01-09 19:18 UTC, pLeminoq commented on module/pattern/launch/src/main/java/org/openbase/jul/pattern/launch/AbstractLauncher.java
> +    private static final SyncObject WAITING_TASK_LIST_LOCK = new SyncObject("WaitingStopLock");
Shouldn't this SyncObject maybe be called `WaitingTaskLock` instead of `WaitingStopLock`?
```suggestion
    private static final SyncObject WAITING_TASK_LIST_LOCK = new SyncObject("WaitingTaskLock");
```

2023-01-09 19:51 UTC, DivineThreepwood commented
I have no issues running `bco` with this `jul` branch, is this a `org.openbase.type` issue? It has actually been released. 
Do you have any further details here?

2023-01-09 20:12 UTC, pLeminoq commented
> I have no issues running `bco` with this `jul` branch, is this a `org.openbase.type` issue? It has actually been released. Do you have any further details here?

I just re-checked and it somewhat works. The startup behavior changed for me, with many warnings being displayed on startup:
```
21:03:16.363 [pool-2-thread-7] WARN  o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RPCServer[/launcher/bco/templateregistry/ctrl]] try again in 60 seconds...                                                      
21:03:16.363 [pool-2-thread-9] WARN  o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RPCServer[/launcher/bco/messageregistry/ctrl]] try again in 60 seconds...                                                       
21:03:16.363 [pool-2-thread-6] WARN  o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RPCServer[/launcher/bco/unitregistry/ctrl]] try again in 60 seconds...                                                          
21:03:16.363 [pool-2-thread-10] WARN  o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RPCServer[/launcher/bco/authenticator/ctrl]] try again in 60 seconds...                                                        
21:03:16.363 [pool-2-thread-5] WARN  o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RPCServer[/launcher/bco/activityregistry/ctrl]] try again in 60 seconds...                                                      
21:03:16.363 [pool-2-thread-1] WARN  o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RPCServer[/launcher/bco/classregistry/ctrl]] try again in 60 seconds...                                                         
21:03:16.364 [pool-2-thread-7] WARN  o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate Subscriber                                                                                                                        
21:03:16.364 [pool-2-thread-9] WARN  o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate Subscriber                                                                                                                        
21:03:16.364 [pool-2-thread-5] WARN  o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate Subscriber                                                                                                                        
21:03:16.364 [pool-2-thread-10] WARN  o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate Subscriber                                                                                                                       
21:03:16.364 [pool-2-thread-1] WARN  o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate Subscriber                                                                                                                        
21:03:16.364 [pool-2-thread-6] WARN  o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate Subscriber                                                                                                                        
21:03:16.365 [pool-2-thread-9] WARN  o.o.j.s.WatchDog     ╚════⚀ TimeoutException                                                                                                                                  
21:03:16.365 [pool-2-thread-7] WARN  o.o.j.s.WatchDog     ╚════⚀ TimeoutException                                                                                                                                  
21:03:16.365 [pool-2-thread-5] WARN  o.o.j.s.WatchDog     ╚════⚀ TimeoutException                                                                                                                                  
21:03:16.365 [pool-2-thread-10] WARN  o.o.j.s.WatchDog     ╚════⚀ TimeoutException                                                                                                                                 
21:03:16.365 [pool-2-thread-6] WARN  o.o.j.s.WatchDog     ╚════⚀ TimeoutException                                                                                                                                  
21:03:16.365 [pool-2-thread-1] WARN  o.o.j.s.WatchDog     ╚════⚀ TimeoutException                                                                                                                                  
21:03:16.365 [pool-2-thread-9] WARN  o.o.j.s.WatchDog ===================================== 
```
Still it will launch and launching a second `bco-test` instance will throw the desired error. However, it will not shutdown properly. Furthermore, if I start `bco-registry` while `bco-test` is still running, it does not detect that another instance is already there.

2023-01-09 21:34 UTC, DivineThreepwood commented
I do not have the same startup / shutdown issues, however I could reproduce a deadlock within the shutdown routine that I will address next.

2023-01-11 00:21 UTC, DivineThreepwood commented
Deadlock has been fixed.

2023-01-11 00:48 UTC, DivineThreepwood commented
> I just re-checked and it somewhat works. The startup behavior changed for me, with many warnings being displayed on startup: 
Your show output is not related to this PR since none of the new shutdown messages are included. It seems like bco still builds again the dev version of `jul` and the two bco instances just interfere with each other that then causes the timeouts. Please make sure again, that you are on the right jul branch `88-avoid-redundant-launcher-execution-by-detecting-already-running-launchers-on-network` with the latest hash `ed92f9ff` and performed a new installation via the `install.sh` script. Than please make sure that the bco binaries referred by your PATH variable actually link to the newly build ones. If this did not help we might have a deployment / local build issue that needs further investigation (e.g: gradle cache issues / unresolvable org.openbase.type dependency that forces gradle to stick to the old jul version).

2023-01-19 19:38 UTC, pLeminoq approved these changes

2023-01-19 19:42 UTC, merged